name: "pooch-cache"
description: "Caches pooches cache"
inputs:
  name:
    description: "The name of the cache"
    required: true
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5

    - shell: bash
      run: python -m pip install pooch

    - shell: python
      id: get-pooch-cache-path
      run: |
        import os
        import pooch

        with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"pooch-cache-path={pooch.os_cache('${{ inputs.name }}')}")
  
    - name: Cache pooch cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.get-pooch-cache-path.outputs.pooch-cache-path }}
        key: pooch-cache-${{ inputs.name }}
        enableCrossOsArchive: true
